_fw_name: CommonAdapter
_fw_q_type: SLURM
_fw_template_file: /path/to/your/config/queue_template.slurm
rocket_launch: rlaunch -c /path/to/your/config singleshot > out
# nodes: 1
# ntasks_per_node: 32
# walltime: 00:30:00
# queue: bansil
# job_name: test
pre_rocket: 
#post_rocket: "[ -s openmx.out ] && cat openmx.out >> openmx.scfout"
post_rocket:
# mem: 100G
logdir: /path/to/your/logs
